### ISSUE TITLE
Fail "ETH GET ADDRESS"

### ISSUE THREAD

**Issue by Eddy-orbs** [btchip/ledger-android-library#1]
Hi Your library is very helpful for my project. Really appreciated.

Recently, ETH app is updated to 1.9.11 and this version does not work with android library.
There is timeout for android device receiving data.
(USB connection work. BLE connection does not work)

Would you help how this can be fixed?

Here is log:

-------

2021-11-08 13:55:24.429 27563-27563/com.ledger.demolib I/ViewRootImpl@8d45b48[MainActivity]: ViewPostIme pointer 0
2021-11-08 13:55:24.500 27563-27563/com.ledger.demolib I/ViewRootImpl@8d45b48[MainActivity]: ViewPostIme pointer 1
2021-11-08 13:55:24.502 27563-32618/com.ledger.demolib D/LedgerDeviceBLE: Begin clear queue
2021-11-08 13:55:24.502 27563-32618/com.ledger.demolib D/LedgerDeviceBLE: End clear queue
2021-11-08 13:55:24.503 27563-32618/com.ledger.demolib D/LedgerDeviceBLE: => b001000000
2021-11-08 13:55:24.503 27563-32618/com.ledger.demolib D/LedgerDeviceBLE: => Fragment 0500000005b001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
2021-11-08 13:55:24.583 27563-32618/com.ledger.demolib D/LedgerDeviceBLE: Received GATT_CHARACTERISTIC_WRITE 13d63400-2c97-0004-0002-4c6564676572 GATT_SUCCESS
2021-11-08 13:55:24.583 27563-32618/com.ledger.demolib D/LedgerDeviceBLE: Received GATT_CHARACTERISTIC_CHANGED 13d63400-2c97-0004-0001-4c6564676572
2021-11-08 13:55:24.583 27563-32618/com.ledger.demolib D/LedgerDeviceBLE: <= Fragment 05000000150108457468657265756d06312e392e313101029000
2021-11-08 13:55:24.583 27563-32618/com.ledger.demolib D/LedgerDeviceBLE: <= 0108457468657265756d06312e392e313101029000
2021-11-08 13:55:24.584 27563-32618/com.ledger.demolib D/LedgerDeviceBLE: Begin clear queue
2021-11-08 13:55:24.585 27563-32618/com.ledger.demolib D/LedgerDeviceBLE: End clear queue
2021-11-08 13:55:24.585 27563-32618/com.ledger.demolib D/LedgerDeviceBLE: => e002010111048000002c8000003c8000000000000000
2021-11-08 13:55:24.585 27563-32618/com.ledger.demolib D/LedgerDeviceBLE: => Fragment 0500000016e002010111048000002c8000003c800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
2021-11-08 13:55:24.672 27563-32618/com.ledger.demolib D/LedgerDeviceBLE: Received GATT_CHARACTERISTIC_WRITE 13d63400-2c97-0004-0002-4c6564676572 GATT_SUCCESS

**2021-11-08 13:55:39.678 27563-32618/com.ledger.demolib W/System.err: IO_ERROR com.ledger.lib.LedgerException: Timeout**
2021-11-08 13:55:39.680 27563-32618/com.ledger.demolib W/System.err:     at com.ledger.lib.transport.LedgerDeviceBLE.waitEvent(LedgerDeviceBLE.java:137)
2021-11-08 13:55:39.680 27563-32618/com.ledger.demolib W/System.err:     at com.ledger.lib.transport.LedgerDeviceBLE.waitEvent(LedgerDeviceBLE.java:124)
2021-11-08 13:55:39.680 27563-32618/com.ledger.demolib W/System.err:     at com.ledger.lib.transport.LedgerDeviceBLE.exchange(LedgerDeviceBLE.java:275)
2021-11-08 13:55:39.680 27563-32618/com.ledger.demolib W/System.err:     at com.ledger.lib.utils.ApduExchange.exchangeApdu(ApduExchange.java:76)
2021-11-08 13:55:39.680 27563-32618/com.ledger.demolib W/System.err:     at com.ledger.lib.utils.ApduExchange.exchangeApdu(ApduExchange.java:139)
2021-11-08 13:55:39.680 27563-32618/com.ledger.demolib W/System.err:     at com.ledger.lib.apps.eth.Eth.getWalletAddress(Eth.java:96)
2021-11-08 13:55:39.681 27563-32618/com.ledger.demolib W/System.err:     at com.ledger.demolib.Tasks$EthGetAddress.doInBackground(Tasks.java:293)
2021-11-08 13:55:39.681 27563-32618/com.ledger.demolib W/System.err:     at com.ledger.demolib.Tasks$EthGetAddress.doInBackground(Tasks.java:278)
2021-11-08 13:55:39.681 27563-32618/com.ledger.demolib W/System.err:     at android.os.AsyncTask$3.call(AsyncTask.java:394)
2021-11-08 13:55:39.681 27563-32618/com.ledger.demolib W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2021-11-08 13:55:39.681 27563-32618/com.ledger.demolib W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
2021-11-08 13:55:39.681 27563-32618/com.ledger.demolib W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2021-11-08 13:55:39.682 27563-32618/com.ledger.demolib W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2021-11-08 13:55:39.682 27563-32618/com.ledger.demolib W/System.err:     at java.lang.Thread.run(Thread.java:923)
2021-11-08 13:55:39.699 27563-27563/com.ledger.demolib D/Toast: show: caller = com.ledger.demolib.MainActivity.toast:145 
2021-11-08 13:55:39.699 27563-27563/com.ledger.demolib I/Toast: show: focusDisplayId = 0, isFocusInDesktop = false mCustomDisplayId=-1 isDexDualMode=false
2021-11-08 13:55:39.700 27563-27563/com.ledger.demolib I/Toast: show: isActivityContext = false
2021-11-08 13:55:39.720 27563-27563/com.ledger.demolib V/ToastPresenter: Text: Frro in android.widget.ToastPresenter@73345f6
2021-11-08 13:55:39.725 27563-31953/com.ledger.demolib D/NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::BpCustomFrequencyManager()
2021-11-08 13:55:39.737 27563-27563/com.ledger.demolib D/InputTransport: Input channel constructed: 'aaac45b', fd=95
2021-11-08 13:55:39.738 27563-27563/com.ledger.demolib I/ViewRootImpl@ec346cd[Toast]: setView = android.widget.LinearLayout@845cb82 TM=true
2021-11-08 13:55:39.754 27563-27563/com.ledger.demolib I/SurfaceControl: assignNativeObject: nativeObject = 0 Surface(name=null)/@0x2457293 / android.view.SurfaceControl.readFromParcel:1117 android.view.IWindowSession$Stub$Proxy.relayout:1820 android.view.ViewRootImpl.relayoutWindow:9130 android.view.ViewRootImpl.performTraversals:3420 android.view.ViewRootImpl.doTraversal:2669 android.view.ViewRootImpl$TraversalRunnable.run:10092 android.view.Choreographer$CallbackRecord.run:1010 android.view.Choreographer.doCallbacks:809 android.view.Choreographer.doFrame:744 android.view.Choreographer$FrameDisplayEventReceiver.run:995 
2021-11-08 13:55:39.755 27563-27563/com.ledger.demolib I/ViewRootImpl@ec346cd[Toast]: Relayout returned: old=(0,88,1768,2208) new=(611,1940,1156,2040) req=(545,100)0 dur=11 res=0x7 s={true 535342459744} ch=true fn=-1
2021-11-08 13:55:39.758 27563-27563/com.ledger.demolib I/ViewRootImpl@ec346cd[Toast]: [DP] dp(1) 0 android.view.ViewRootImpl.reportNextDraw:11078 android.view.ViewRootImpl.performTraversals:3915 android.view.ViewRootImpl.doTraversal:2669 
2021-11-08 13:55:39.758 27563-27563/com.ledger.demolib I/ViewRootImpl@ec346cd[Toast]: [DP] pd() Asnyc report
2021-11-08 13:55:39.759 27563-27563/com.ledger.demolib I/ViewRootImpl@ec346cd[Toast]: mAttachInfo.mThreadedRenderer.draw, mView = android.widget.LinearLayout{845cb82 V.E...... ......ID 0,0-545,100} w = 545 h = 100
2021-11-08 13:55:39.771 27563-31953/com.ledger.demolib D/OpenGLRenderer: GPIS:: SetUp Pid : 27563    Tid : 31953
2021-11-08 13:55:39.772 27563-27563/com.ledger.demolib I/ViewRootImpl@ec346cd[Toast]: [DP] pdf(0) 0 android.view.ViewRootImpl.lambda$performDraw$1$ViewRootImpl:4743 android.view.-$$Lambda$ViewRootImpl$DJd0VUYJgsebcnSohO6h8zc_ONI.run:6 android.os.Handler.handleCallback:938 
2021-11-08 13:55:39.772 27563-27563/com.ledger.demolib I/ViewRootImpl@ec346cd[Toast]: [DP] rdf()
2021-11-08 13:55:41.726 27563-27563/com.ledger.demolib E/SurfaceFlinger: resetPartialBlurMask failed to transact: -1
2021-11-08 13:55:41.726 27563-27563/com.ledger.demolib I/ViewRootImpl@ec346cd[Toast]: dispatchDetachedFromWindow
2021-11-08 13:55:41.726 27563-27563/com.ledger.demolib I/SurfaceControl: nativeRelease nativeObject s[531047925936]
2021-11-08 13:55:41.726 27563-27563/com.ledger.demolib I/SurfaceControl: nativeRelease nativeObject e[531047925936]
2021-11-08 13:55:41.751 27563-27563/com.ledger.demolib D/InputTransport: Input channel destroyed: 'aaac45b', fd=95
2021-11-08 13:55:47.649 27563-27563/com.ledger.demolib I/ViewRootImpl@8d45b48[MainActivity]: ViewPostIme pointer 0
2021-11-08 13:55:47.726 27563-27563/com.ledger.demolib I/ViewRootImpl@8d45b48[MainActivity]: ViewPostIme pointer 1
2021-11-08 13:55:47.728 27563-32618/com.ledger.demolib D/LedgerDeviceBLE: Begin clear queue
2021-11-08 13:55:47.728 27563-32618/com.ledger.demolib D/LedgerDeviceBLE: End clear queue
2021-11-08 13:55:47.728 27563-32618/com.ledger.demolib D/LedgerDeviceBLE: => b001000000
2021-11-08 13:55:47.728 27563-32618/com.ledger.demolib D/LedgerDeviceBLE: => Fragment 0500000005b001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
2021-11-08 13:55:47.802 27563-32618/com.ledger.demolib D/LedgerDeviceBLE: Received GATT_CHARACTERISTIC_WRITE 13d63400-2c97-0004-0002-4c6564676572 GATT_SUCCESS
2021-11-08 13:55:47.803 27563-32618/com.ledger.demolib D/LedgerDeviceBLE: Received GATT_CHARACTERISTIC_CHANGED 13d63400-2c97-0004-0001-4c6564676572
2021-11-08 13:55:47.803 27563-32618/com.ledger.demolib D/LedgerDeviceBLE: <= Fragment 05000000150108457468657265756d06312e392e313101029000
2021-11-08 13:55:47.803 27563-32618/com.ledger.demolib D/LedgerDeviceBLE: <= 0108457468657265756d06312e392e313101029000
2021-11-08 13:55:47.814 27563-27563/com.ledger.demolib D/Toast: show: caller = com.ledger.demolib.MainActivity.toast:145 
2021-11-08 13:55:47.814 27563-27563/com.ledger.demolib I/Toast: show: focusDisplayId = 0, isFocusInDesktop = false mCustomDisplayId=-1 isDexDualMode=false
2021-11-08 13:55:47.814 27563-27563/com.ledger.demolib I/Toast: show: isActivityContext = false
2021-11-08 13:55:47.821 27563-27563/com.ledger.demolib D/demolib: Ethereum 1.9.11 1
2021-11-08 13:55:47.828 27563-27563/com.ledger.demolib V/ToastPresenter: Text: Hot  in android.widget.ToastPresenter@79d48da
2021-11-08 13:55:47.830 27563-31953/com.ledger.demolib D/NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::BpCustomFrequencyManager()
2021-11-08 13:55:47.836 27563-27563/com.ledger.demolib D/InputTransport: Input channel constructed: '5492259', fd=88
2021-11-08 13:55:47.837 27563-27563/com.ledger.demolib I/ViewRootImpl@d2ac201[Toast]: setView = android.widget.LinearLayout@1718a6 TM=true
2021-11-08 13:55:47.848 27563-27563/com.ledger.demolib I/SurfaceControl: assignNativeObject: nativeObject = 0 Surface(name=null)/@0x9bc42e7 / android.view.SurfaceControl.readFromParcel:1117 android.view.IWindowSession$Stub$Proxy.relayout:1820 android.view.ViewRootImpl.relayoutWindow:9130 android.view.ViewRootImpl.performTraversals:3420 android.view.ViewRootImpl.doTraversal:2669 android.view.ViewRootImpl$TraversalRunnable.run:10092 android.view.Choreographer$CallbackRecord.run:1010 android.view.Choreographer.doCallbacks:809 android.view.Choreographer.doFrame:744 android.view.Choreographer$FrameDisplayEventReceiver.run:995 
2021-11-08 13:55:47.849 27563-27563/com.ledger.demolib I/ViewRootImpl@d2ac201[Toast]: Relayout returned: old=(0,88,1768,2208) new=(653,1940,1114,2040) req=(461,100)0 dur=7 res=0x7 s={true 535342459744} ch=true fn=-1
2021-11-08 13:55:47.850 27563-27563/com.ledger.demolib I/ViewRootImpl@d2ac201[Toast]: [DP] dp(1) 0 android.view.ViewRootImpl.reportNextDraw:11078 android.view.ViewRootImpl.performTraversals:3915 android.view.ViewRootImpl.doTraversal:2669 
2021-11-08 13:55:47.850 27563-27563/com.ledger.demolib I/ViewRootImpl@d2ac201[Toast]: [DP] pd() Asnyc report
2021-11-08 13:55:47.850 27563-27563/com.ledger.demolib I/ViewRootImpl@d2ac201[Toast]: mAttachInfo.mThreadedRenderer.draw, mView = android.widget.LinearLayout{1718a6 V.E...... ......ID 0,0-461,100} w = 461 h = 100
2021-11-08 13:55:47.853 27563-31953/com.ledger.demolib D/OpenGLRenderer: GPIS:: SetUp Pid : 27563    Tid : 31953
2021-11-08 13:55:47.855 27563-27563/com.ledger.demolib I/ViewRootImpl@d2ac201[Toast]: [DP] pdf(0) 0 android.view.ViewRootImpl.lambda$performDraw$1$ViewRootImpl:4743 android.view.-$$Lambda$ViewRootImpl$DJd0VUYJgsebcnSohO6h8zc_ONI.run:6 android.os.Handler.handleCallback:938 
2021-11-08 13:55:47.855 27563-27563/com.ledger.demolib I/ViewRootImpl@d2ac201[Toast]: [DP] rdf()
2021-11-08 13:55:49.830 27563-27563/com.ledger.demolib E/SurfaceFlinger: resetPartialBlurMask failed to transact: -1
2021-11-08 13:55:49.830 27563-27563/com.ledger.demolib I/ViewRootImpl@d2ac201[Toast]: dispatchDetachedFromWindow
2021-11-08 13:55:49.830 27563-27563/com.ledger.demolib I/SurfaceControl: nativeRelease nativeObject s[531047990704]
2021-11-08 13:55:49.830 27563-27563/com.ledger.demolib I/SurfaceControl: nativeRelease nativeObject e[531047990704]
2021-11-08 13:55:49.842 27563-27563/com.ledger.demolib D/InputTransport: Input channel destroyed: '5492259', fd=88

**Comment by spacelinkers** [comment]
Hello,
We are having the same issue after upgrading to new firmware v-2.0.0
Would you please help to solve this issue as this library is very essential to our project.

**Comment by Armaan-Ul-Islam** [comment]
Same here.

**IO_ERROR com.ledger.lib.LedgerException: Timeout**

Results in timeout error in case of any hardware wallet communications like: getting addresses, signing transactions, etc.
Ledger USB works fine with the same ledger Nano X device but Ledger BLE fails.

Ethereum app version: 1.9.11/ 1.9.13
Ledger Nano X firmware version: 2.0.0

@btchip

**Comment by Eddy-orbs** [comment]
@spacelinkers @Armaan-Ul-Islam 

I made a fix finally and it works.

Please check 2 commits and apply those on your own forked ledger lib and build aar.

https://github.com/Eddy-orbs/ledger-android-library/commit/11bc7cd098605fda0322c0baa22cee82d8a818af
https://github.com/Eddy-orbs/ledger-management-android-library/commit/bf1c7d8c39df4298b10f9539ff9d3c2b1412a3c6
